spring:
  application:
    name: tour-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8766
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true  # Use IP address instead of hostname
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: tour-service  # Use the service name as the hostname
