spring:
  application:
    name: tour-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8766
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: false
    instance-id: tour-service
    hostname: localhost
