
spring.application.name=api-gateway
server.port=8070

eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.preferIpAddress=true
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}

# Gateway Discovery Locator (Enable if needed)
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lowerCaseServiceId=true

spring.cloud.discovery.enabled=true
#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lowerCaseServiceId=true
# eureka.instance.preferIpAddress = true
# eureka.instance.hostname=localhost

